apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubixnodes-jm-mainnet
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubixnodes-jm-mainnet
  template:
    metadata:
      labels:
        app: rubixnodes-jm-mainnet
    spec:
      containers:
        - name: rubixnode-sha256-1
          image: gcr.io/optimal-courage-425706-k2/github.com/jupiter-meta/rubix-docker
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rubix-main-storage
              mountPath: /app/rubix  # Adjust this path as per your application's requirements
      volumes:
        - name: rubix-main-storage
          persistentVolumeClaim:
            claimName: rubix-main-pvc  # PVC name for the storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubix-main-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce  # Adjust as per your requirements
  resources:
    requests:
      storage: 30Gi  # Adjust the storage size as per your requirements
