apiVersion: v1
kind: PersistentVolume
metadata:
  name: rubixnode-pv
  namespace: default
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  hostPath:
    path: "/app" # Example path, adjust based on your storage setup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubixnodestorage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubixnode
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubixnode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rubixnode
    spec:
      containers:
        - name: rubixnode-1
          image: gcr.io/optimal-courage-425706-k2/github.com/jupiter-meta/rubix-docker
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5050
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: "/app" # Example mount path, adjust as needed
              name: rubixnode-vol
      volumes:
        - name: rubixnode-vol
          persistentVolumeClaim:
            claimName: rubixnodestorage
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rubixnode-hpa-seb8
  namespace: default
  labels:
    app: rubixnode
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rubixnode
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rubixnode-service
  namespace: default
  labels:
    app: rubixnode
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.237.53
  clusterIPs:
    - 34.118.237.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 5050-to-5050-tcp
      nodePort: 30710
      port: 5050
      protocol: TCP
      targetPort: 5050
    - name: 5002-to-5002-tcp
      nodePort: 31979
      port: 5002
      protocol: TCP
      targetPort: 5002
    - name: 4002-to-4002-tcp
      nodePort: 32296
      port: 4002
      protocol: TCP
      targetPort: 4002
    - name: 20000-to-20000-tcp
      port: 20000
      protocol: TCP
      targetPort: 20000
    - name: 11500-to-11500-tcp
      port: 11500
      protocol: TCP
      targetPort: 11500
    - name: 22010-to-22010-tcp
      port: 22010
      protocol: TCP
      targetPort: 22010
    - name: 8081-to-8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
