apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubixnodes-jm-mainnet
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rubixnodes-jm-mainnet
  template:
    metadata:
      labels:
        app: rubixnodes-jm-mainnet
    spec:
      containers:
        - name: rubixnode-sha256-1
          image: gcr.io/optimal-courage-425706-k2/github.com/jupiter-meta/rubix-docker
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rubix-main-storage
              mountPath: /app
      volumes:
        - name: rubix-main-storage
          persistentVolumeClaim:
            claimName: rubix-main-pvc
