apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubix-main-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Must match the PV access mode
  resources:
    requests:
      storage: 30Gi  # Amount of storage requested
  storageClassName: rubix-storage-class  # Name of the StorageClass
