apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubixnodestorage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
