apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rubixnodestorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
  volumeName: rubixnode-pv   # Name of the PersistentVolume to claim
