apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubixnode
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rubixnode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rubixnode
    spec:
      containers:
        - name: rubixnode-1
          image: gcr.io/optimal-courage-425706-k2/github.com/jupiter-meta/rubix-docker
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app" # Example mount path, adjust as needed
              name: rubixnode-vol
          workingDir: "/app"
      volumes:
        - name: rubixnode-vol
          persistentVolumeClaim:
            claimName: rubixnodestorage
