apiVersion: v1
kind: Service
metadata:
  name: rubixnode-service
  namespace: default
  labels:
    app: rubixnode
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.237.53
  clusterIPs:
    - 34.118.237.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 5050-to-5050-tcp
      nodePort: 30710
      port: 5050
      protocol: TCP
      targetPort: 5050
    - name: 5002-to-5002-tcp
      nodePort: 31979
      port: 5002
      protocol: TCP
      targetPort: 5002
    - name: 4002-to-4002-tcp
      nodePort: 32296
      port: 4002
      protocol: TCP
      targetPort: 4002
    - name: 20000-to-20000-tcp
      port: 20000
      protocol: TCP
      targetPort: 20000
    - name: 11500-to-11500-tcp
      port: 11500
      protocol: TCP
      targetPort: 11500
    - name: 22010-to-22010-tcp
      port: 22010
      protocol: TCP
      targetPort: 22010
    - name: 8081-to-8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
