apiVersion: v1
kind: PersistentVolume
metadata:
  name: rubixnode-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  hostPath:
    path: /mnt/data   # Replace with your desired host path
